version: "3.9"

services:

  caddy:
    image: "docker.io/hectormolinero/caddy2:latest"
    restart: "on-failure:3"
    hostname: "caddy"
    networks:
      - "hblock-resolver"
    ports:
      - "127.0.0.153:80:80/tcp"
      - "127.0.0.153:443:443/tcp"
      - "127.0.0.153:853:853/tcp"
    volumes:
      - "./config/caddy/Caddyfile.cue:/etc/caddy/Caddyfile.cue:ro"
      - "caddy-data:/var/lib/caddy/"
    environment:
      TLS_DOMAIN: "${TLS_DOMAIN}"
      TLS_EMAIL: "${TLS_EMAIL}"
      TLS_MODULE: "${TLS_MODULE}"
      TLS_CA: "${TLS_CA}"
    command: ["run", "--config", "/etc/caddy/Caddyfile.cue", "--adapter", "cue"]

  hblock-resolver:
    image: "docker.io/hectorm/hblock-resolver:latest"
    restart: "on-failure:3"
    hostname: "hblock-resolver"
    networks:
      - "hblock-resolver"
    ports:
      - "127.0.0.153:53:53/udp"
      - "127.0.0.153:53:53/tcp"
    volumes:
      - "hblock-resolver-data:/var/lib/knot-resolver/"

networks:

  hblock-resolver:

volumes:

  caddy-data:

  hblock-resolver-data:
